name: myapp

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    volumes:
      - ./backend:/workspace
    secrets:
      - my-password
    env_file:
      - dev.env

secrets:
  my-password:
    file: dev.env
