name: myapp

services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: next
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/workspace

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    volumes:
      - ./backend:/workspace
    env_file:
      - .env.local
      # secrets:
      # - my-password

      # secrets:
      #   my-password:
      #     file: dev.env

